ajax/urls.py
from django.conf.urls import url, patterns


urlpatterns = patterns(
    '',
    url(r'^postcomment/(?P<post_type>[a-zA-Z]+)/(?P<post_id>[0-9]+)$', 'ajax.views.postcomment', name='postcomment'),
    url(r'^vote/(?P<post_type>[a-zA-Z]+)$', 'ajax.views.vote', name='vote'),
)

dealhunters/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns(
    '',
    # Examples:
    # url(r'^$', 'bod.views.home', name='home'),
    # url(r'^bod/', include('bod.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url('^help', 'bod.views.gethelp', name='help'),
    url('^about', 'bod.views.about', name='about'),
    url('^user', 'userprofile.views.userdetails', name='userdetails'),
    url('^vote', include('vote.urls', namespace='vote')),
    url('^feedback', 'bod.views.feedback', name='feedback'),
    url('^login', 'bod.views.login', name='login'),
    url('^logout', 'bod.views.logout', name='logout'),
    #url('^loggedin$', 'bod.views.loggedin'),
    #url('^loggedout$', 'bod.views.loggedout'),
    url('^logininvalid$', 'bod.views.logininvalid'),
    url('^auth$', 'bod.views.auth_view'),
    url('^register$', 'bod.views.register', name='register'),
    url('^register_success$', 'bod.views.register_success', name='register_success'),
    url(r'^deals/', include('deals.urls', namespace='deals')),
    url(r'^submit$', 'deals.views.submit', name='submit'),
    url(r'^asja/', include('ajax.urls', namespace='ajax')),
    url(r'^$', 'deals.views.dealslist', name='index'),
)


if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT}))

deals/urls.py
__author__ = 'kumar'

from django.conf.urls import url, patterns


urlpatterns = patterns(
    '',
    url(r'^view/(?P<deal_slug>[a-zA-Z\-_0-9]+)', 'deals.views.view', name='details'),
    url(r'^visit$', 'deals.views.visit', name='visit'),
#    url(r'^(?P<category>[\w]+)/(?P<sort>[\w]+)/$', 'deals.views.dealslist', name='catlist'),
    url(r'^(?P<category>[a-zA-z]+)/$', 'deals.views.dealslist', name='sortlist'),
    url(r'^$', 'deals.views.dealslist', name='alllist'),
)

deals/forms.py
__author__ = 'kumar'

from django import forms
from deals.models import *
from sorl.thumbnail.fields import ImageFormField


class PostDealForm(forms.Form):
    DEAL_TYPE_ONLINE = 1
    DEAL_TYPE_INSTORE = 2
    DEAL_TYPE_BOTH = 3
    DEAL_TYPE_CHOICES = (
        (DEAL_TYPE_ONLINE, 'Online'),
        (DEAL_TYPE_INSTORE, 'In-store'),
        (DEAL_TYPE_BOTH, 'Online & Instore')
    )

    DESCRIPTION_PLACEHOLDER = 'Description of the deal goes here. Explain to the community how this is good deal and\
    how it can be availed. List Features of the product so the community can evaluate and from this deal.'
    INSTRUCTIONS_PLACEHOLDER = 'If any instructions are applicable on how to grab the deal, mention it here. \
    This shall be additional information shared for better understanding.'


    deal_type = forms.ChoiceField(choices=DEAL_TYPE_CHOICES, required=True,
                                  help_text="Deal type whether it is an Online deal or Instore Deal")
    category = forms.ChoiceField(choices=Deals.DEAL_CATEGORY, required=True)
    price = forms.DecimalField(required=True, help_text='Enter 0 if price is not applicable')
    title = forms.CharField(max_length=100, required=True,
                            widget=forms.TextInput(attrs={'placeholder': 'Enter Title of the Deal (Max 100 chars)'}),
                            help_text='Sample Title: Dell XPS 12 core i7, 8GB RAM for 82K @ dell.co.in')
    url = forms.URLField(max_length=255, required=True,
                         widget=forms.TextInput(attrs={'placeholder': 'Enter URL of the Deal in case of Online Deal'}),
                         help_text='Enter valid URL of the deal if it is an oline deal')
    description = forms.CharField(widget=forms.Textarea(attrs={'placeholder': DESCRIPTION_PLACEHOLDER}), required=True)
    tags = forms.CharField(required=False,
                           widget=forms.TextInput(attrs={'placeholder': 'Tag the deal, separate by comma for multiple tags'}),
                           help_text='Good tags help other members search and identify deals specifically.')
    coupon = forms.CharField(max_length=100, required=False,
                             widget=forms.TextInput(attrs={'placeholder': 'Enter Coupon code for the deal if any'}),
                             help_text='If coupons are to be used to get the lowest price, please mention it here')
    from_date = forms.DateTimeField(required=False, widget=forms.DateTimeInput,
                                    help_text='Date from when the deal is active')
    to_date = forms.DateTimeField(required=False, widget=forms.DateTimeInput,
                                  help_text='Date after which deal will Expire')
    instructions = forms.CharField(required=False, widget=forms.Textarea(attrs={'placeholder': INSTRUCTIONS_PLACEHOLDER}),
                                   help_text='Any additional instructions which could help community grab the deal')
    image = ImageFormField(required=False, widget=forms.FileInput)
    image_url = forms.URLField(required=False)
    email = forms.EmailField(required=True, help_text='Do not Worry, Your email is SAFE with us.')

    def clean_from_date(self):
        from_date = self.cleaned_data.get('from_date')
        to_date = self.cleaned_data.get('to_date')

        if from_date < to_date:
            raise forms.ValidationError('From date cannot be less than to date.')

        return from_date

deals/views.py
# Create your views here.

from django.shortcuts import render_to_response
from django.http import HttpResponseRedirect, HttpResponseBadRequest, HttpResponse, Http404
from deals.models import Deals, Comments, Stores, content_file_name, Visits
from django.contrib.auth.decorators import login_required
from common.frequentfuncs import *
from django.db.models import Count
import logging
from datetime import date, timedelta
from django.db.models.query import QuerySet
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.core.context_processors import csrf
from deals.forms import PostDealForm
from django.template.defaultfilters import slugify
from urlparse import urlparse
from django.contrib.auth.hashers import make_password
from django.contrib import auth
import datetime
from common.decors import *
from itertools import chain
from django.core.exceptions import ValidationError
from django.core.validators import validate_email
from django.db import transaction
from sorl.thumbnail import get_thumbnail
import urllib2
from django.core.files import File
from urlparse import urlparse
from django.core.files.base import ContentFile
from django.core.urlresolvers import reverse
from django.utils.timezone import now

logr = logging.getLogger()


def dealslist(request, category=None):
    (args, params) = common_deal_funcs(request)
    # TODO: Logic to get category needs to be updated to get preference from cookies
    cat_num = False
    if not category:
        category = 'all topics'

    # Check if the Category Matches
    if category and category.lower() != 'all topics':
        cat_num = validate_category(category)
        if cat_num:
            params['category'] = category
            deals = Deals.objects.filter(category=cat_num).select_related('store', 'user')
        else:
            return HttpResponseBadRequest()
    else:
        params['category'] = 'All Topics'
        deals = Deals.objects.all().select_related('store_id', 'user_id')

    # Annotate and get the number of comments
    deals = deals.annotate(commentcount=Count('comments'))

    # Check if the sort order matches.
    orderby = '-date_time'
    sort = request.GET.get('sort', None)
    if sort and sort in SORT_ORDER:
        params['sort'] = sort
        if sort == 'hot':
            deals = deals.filter(expired=False)
            orderby = '-temperature'
        elif sort == 'discussed':
            orderby = '-commentcount'

    # TODO: Pagination needs to be changed as per user's preference of number of items/per page from cookie
    items_per_page = 10
    start = 0
    end = items_per_page
    if request.GET:
        try:
            page = int(request.GET['page'])
        except:
            page = 1
        start = (page - 1) * items_per_page if page > 0 else 0
        end = page * items_per_page if page > 0 else items_per_page
    else:
        page = 1

    start = 0 if start < 0 else start
    #end = end - 1 if end > 1 else end

    params['items_per_page'] = items_per_page
    params['page'] = page

    totitems = deals.count() + 1
    end = totitems if end >= totitems else end
    params['totitems'] = totitems

    deals = deals.order_by(orderby)[start:end]

    # Call the pagination common function to get the page numbers
    pagination = paginate(page, totitems, items_per_page, True)

    # Get sidebar contents
    params['sidebar'] = get_sidebar(cat_num, False)

    args['deals'] = deals
    args['params'] = params
    args['pagination'] = pagination

    output = ''
    for key, value in args.iteritems():
        if type(value) == dict:
            for key1, value1 in value.iteritems():
                if type(value1) == QuerySet:
                    for data in value1:
                        output = output + 'key1 : ' + key1 + data.title + '</br>'
                elif type(value1) == tuple or type(value1) == list:
                    pass
                else:
                    output = output +  str(value1) + '</br>'
        elif type(value) == QuerySet:
            for data in value:
                output = output + 'key : ' + key + data.title + '</br>'

    #return HttpResponse('<p>%s</p>' % output)
    return render_to_response('deals/index.html', args)


def view(request, deal_slug):
    # TODO: Currently sort order and category preference is not stored in cookies, need to enhance it later
    (args, params) = common_deal_funcs(request)

    # TODO: This logic needs to be changed to get comments/page preferencefrom cookies
    try:
        comments_per_page = params['comments_per_page'] = int(request.GET.get('cpp'))
    except:
        comments_per_page = params['comments_per_page'] = 10
    # Number of Top comments
    num_top_comments = 3
    # Get comment_page
    try:
        commentspage = params['commentspage'] = int(request.GET.get('cpage', 1))
    except:
        commentspage = params['commentspage'] = 1

    deals = Deals.objects.filter(identity=deal_slug).annotate(totcomments=Count('comments')).select_related('Store', 'User', 'Comments')
    if not deals:
        return Http404('<h2>Page not found</h2>')

    deal = deals[0]

    totcomments = deal.totcomments + 1
    totpages = int(totcomments / comments_per_page) + 1 if totcomments % comments_per_page !=0 else totcomments / comments_per_page
    if commentspage > totpages:
        return HttpResponseRedirect(reverse('index'))

    start = (commentspage - 1) * comments_per_page if commentspage > 0 else 0
    end = commentspage * comments_per_page if commentspage > 0 else commentspage
    args['category'] = category_words(deal.category)
    args['category'] = args['category'] if args['category'] else 'computers'

    set_comments = deal.comments_set
    start = 0 if start < 0 else start
    end = totcomments if end >= totcomments else end

    topcomments = set_comments.select_related('User').extra(select={'topcomms':'likes-unlikes-abusive'})
    topcomments = topcomments.order_by('-topcomms')[0:num_top_comments]
    comments = set_comments.select_related('User')
    comments = comments.order_by('date_time')[start: end]
    comment_pagination = paginate(params['commentspage'], deal.totcomments, params['comments_per_page'])

    #Get side bar
    params['sidebar'] = get_sidebar(False, False)

    args['deal'] = deal
    args['topcomments'] = topcomments
    args['comments'] = comments
    args['comment_pagination'] = comment_pagination
    args['params'] = params
    args.update(csrf(request))
    return render_to_response('deals/details.html', args)


#@transaction.commit_manually
def submit(request):
    (args, params) = common_deal_funcs(request)

    if request.method == 'POST':
        if request.user.is_authenticated():
            request.POST['email'] = request.user.email
        form = PostDealForm(request.POST, request.FILES)
        if form.is_valid():
            data = form.cleaned_data
            tags = ''
            if not request.user.is_authenticated():
                form_email = data.get('email', '')
                params['user'] = get_create_user(form_email, request)

            deal = Deals()
            deal.deal_type = data.get('deal_type')
            deal.category = data.get('category')
            deal.title = data.get('title', 'Title is empty')
            deal.identity = data.get('identity', slugify('%s-%s' % (deal.title, params['last_id']+1)))
            deal.price = data.get('price', 0)
            deal.url = data.get('url')
            image_url = data.get('image_url', '')

            image = data.get('image', '')

            store_url = urlparse(deal.url)
            urlhost = store_url.hostname.split('.')

            if len(urlhost) > 1:
                store = urlhost[-2]
            else:
                store = urlhost[-1] if len(urlhost) == 1 else ''

            deal.store = store

            try:
                store_rec = Stores.objects.get(name=store)
            except:
                store_rec = Stores()
                store_rec.name = store
                store_rec.url = store_url.scheme + '//' + store_url.netloc
                store_rec.views = 0
                store_rec.store_type = 1
                store_rec.save()

            deal.store_id = store_rec
            deal.store_address = data.get('')
            deal.description = data.get('description')
            deal.temperature = 0
            deal.start_date = data.get('from_date')
            deal.end_date = data.get('to_date')
            deal.expired = False
            deal.active = False
            deal.last_made_hot = deal.date_time = now()
            deal.user = params['user']

            tags = data.get('tags', '')
            tag_objs = get_create_tags(tags) if tags else list()
            if image:
                deal.image_url = image
                deal.save()
            elif image_url:
                get_file_from_url(deal, image_url)
            else:
                deal.image_url = ''
                deal.save()

            #transaction.commit()
            if tag_objs:
                for tag_obj in tag_objs:
                    deal_tag = DealTags()
                    deal_tag.deal_id = deal
                    deal_tag.tag_id = tag_obj
                    deal_tag.save()
            args['message'] = 'Thanks for sharing the deal. The deal will appear shortly after moderation.'

            form = PostDealForm()
    else:
        form = PostDealForm()

    #transaction.commit()
    args.update(csrf(request))
    #Get side bar
    params['sidebar'] = get_sidebar(False, False)

    args['form'] = form
    args['params'] = params
    return render_to_response('deals/submit.html', args)


def visit(request):
    (args, params) = common_deal_funcs(request)
    post_id = request.GET.get('deal','')
    if post_id and re.match(r'^[0-9]+$', post_id):
        deal = Deals.objects.filter(pk=post_id).select_related('Store')
        if not deal:

deals/templates/deals/base.html
{% load staticfiles %}
{% load thumbnail %}
{% load bbcode %}

<!DOCTYPE html>
<!--[if IE 8]> 				 <html class="no-js lt-ie9" lang="en" > <![endif]-->
<!--[if gt IE 8]><!-->

<html class="no-js" lang="en" > <!--<![endif]-->

<head>
	<meta charset="utf-8" http-equiv="Content-Type" content="text/html"/>
  	<meta name="viewport" content="width=device-width" />
    <meta name="robot" content="index, follow"/>
    <meta name="description" content="{% block meta_description %}{% endblock meta_description %}"/>
  	<title>BestofDeals - {% block title %}Best Deals, Offers & Coupons{% endblock title %}</title>
	<link rel="stylesheet" href="{% static "css/app.css"  %}">
  	<link rel="stylesheet" href="{% static "css/normalize.css" %}">
  	<link rel="stylesheet" href="{% static "css/foundation.css" %}">
  	<link rel="stylesheet" href="{% static "css/style.css" %}"/>
  	<link href='http://fonts.googleapis.com/css?family=Open+Sans:400,600' rel='stylesheet' type='text/css'>
  	<script type="text/javascript" src="{% static "js/vendor/custom.modernizr.js" %}"></script>
  	<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js"></script>
  	<script type="text/javascript" src="{% static "js/app.js" %}"></script>
    {% block head %}{% endblock head %}
</head>


<body>

<!-- Page Header  with Login Bar-->

<div class="bg-color-three" id="top-nav-wrap">
    <div class="row">
        <div class="large-2 columns">
        </div>
        <div class="large-7 columns">
            <div class="row">
                <nav id="main-nav">
                    <ul>
                        {% block top_nav %}
                            <li><a href="{% url 'deals:alllist' %}" class="inactive f-size-14">HOME</a></li>
                            <li><a href="{% url 'about' %}" class="bg-color-six active f-size-14">ABOUT</a></li>
                            <li><a href="{% url 'blog:index' %}" class="bg-color-six active f-size-14">BLOG</a></li>
                            <li><a href="{% url 'help' %}" class="bg-color-six active f-size-14">HELP</a></li>
                            <li><a href="{% url 'feedback' %}" class="bg-color-six active f-size-14">FEEDBACK</a></li>
                        {% endblock top_nav %}
                    </ul>
                </nav>
            </div>
        </div>
        <div class="large-3 columns">
            <ul id="login-bar" class="right">
                {% if not params.user.is_authenticated %}
                <li id="login">
                    <a id="login-trigger" class="f-size-16">Login<span id="login-arrow" class="small-down-arrow"></span>
                    </a>
                    <div id="login-content">
                        <form method="POST" action="{% url 'login' %}">{% csrf_token %}
                            <label for="username">Username : </label>
                            <input id="username" type="text" name="username" placeholder="Your email address" required>
                            <label for="password">Password : </label>
                            <input id="password" type="password" name="password" placeholder="Password" required>
                            <label for="rememberme"><input type="checkbox" checked="checked" name="rememberme"> Keep me signed in</label>
                            <input type="submit" id="submit" value="Log in" class="small button">
                      </form>
                    </div>
                </li>
                <li><a id="signup" href="{% url 'register' %}" class="f-size-16">Register</a></li>
                {% else %}
                    <ul id="user-logged-in">
                        <li><a class="login-bar-account-menu f-size-16" href="{% url 'userdetails' %}/{{ params.user.username }}">My Profile</a></li>
                        <li><a class="login-bar-account-menu f-size-16" href="{% url 'logout' %}">Logout</a></li>
                    </ul>
                {% endif %}
            </ul>
        </div>
    </div>
</div>

<div class="container bg-color-five">
    <div class="row bg-color-white" id="detail-doc-wrap">
        <!-- Nav & Search Bar-->
        {% block nav_search %}
            <div class="row" id="nav-search">
                {% block nav_left %}
                <div class=" large-6 columns">
                    <nav class="top-bar" id="topics">
                        <section class="top-bar-section">
                            <ul id="topics-nav" class="left">
                                <li class="has-dropdown">
                                    <a >
                                    {{ params.category|title }}
                                    </a>
                                    <ul class="dropdown">
                                        {% block topics %}
                                            {% for cat in params.categories %}
                                                {% if params.category|lower != 'all topics' and forloop.first %}
                                                    <li>
                                                    <a href="{% url 'deals:alllist' %}{% if sort %}all/{{ sort }}{% endif %}" {% if forloop.first %}class="first" {% endif %}>All Topics</a></li>
                                                    </li>
                                                {% elif cat.1 != category %}
                                                    <li>
                                                        <a href="{% url 'deals:alllist' %}{{ cat.1|lower }}/{% if sort %}{{ sort }}{% endif %}" {% if forloop.first %}class="first" {% endif %}>{{ cat.1 }}</a></li>
                                                {% endif %}
                                            {% endfor %}
                                        {% endblock topics %}
                                    </ul>
                                </li>
                            </ul>
                        </section>
                    </nav>
                </div>
                <div class="large-3 columns" id="sort-bar">
                    <span>Sort By : </span>
                    <select id="sorting">
                        <option value="date" {% if params.sort|lower == 'date' %}selected="selected"{% endif %}>Posted Date</option>
                        <option value="hot" {% if params.sort|lower == 'hot' %}selected="selected"{% endif %}>Hotness</option>
                        <option value="discussed" {% if params.sort|lower == 'discussed' %}selected="selected"{% endif %}>Most Commented</option>
                    </select>
                </div>
                {% endblock nav_left %}
                {% block nav_right %}
                <div class="large-3 columns">
                    <form id="search-form">
                        <div class="row collpase">
                            <div class="large-12 columns" id="search-row">
                                <input type="search" name="search" placeholder="Search for posts ..." id="main-search" />
                                <input type="submit" value="GO" id="main-search-submit"/>
                            </div>
                        </div>
                    </form>
                </div>
                {% endblock nav_right %}
            </div>
        {% endblock nav_search %}
    <!-- Main content -->

        <!-- Content -->
        <div class="row" id="content-sidebar">
            {% block main_content %}
            <div class="large-9 columns" id="content">
            </div>
            {% endblock main_content %}
        <!-- Side Bar -->
            {% block sidebar %}
                <div class="large-3 columns hide-for-medium-down" id="sidebar">
                <!-- Share a deal Link-->
                {% block sidebar_submit %}
                <div class="row">
                    <div class="panel" id="submit-button">
                        <span class="large-icon" data-icon="&#xe06a;"></span><span class="submit-text">Have an hot deal to share ? </span>
                        <a  title="Share a Deal with BOD Community" href="{% url 'submit' %}">Share a Deal</a>
                    </div>
                </div>
                {% endblock sidebar_submit %}
                <div class="row small-empty"></div>
                {% block sidebar_snapshot %}
                <div class="row">
                    <div class="large-12 columns" id="snapshot">
                        <div id="snapshot-header">
                            <span class="large-icon color-orange" data-icon="&#xe028;"></span>
                            <h5>Hottest Today</h5>
                        </div>
                        <div class="row" id="snapshot-title-bar">
                            <span class="snapshot-title bg-color-three first selected" id="snapshot-title-1">TODAY</span>
                            <span class="snapshot-title bg-color-three" id="snapshot-title-2">WEEK</span>
                            <span class="snapshot-title bg-color-three" id="snapshot-title-3">MONTH</span>
                            <span class="snapshot-title bg-color-three last" id="snapshot-title-4">ALL</span>
                        </div>
                        <div class="row">
                            <table id="snapshot-table-1" class="snapshot-table visible-table">
                                <tbody>
                                {% for data in params.sidebar.hottoday %}
                                    <tr><td><span class="snapshot-temp">{{ data.temperature }} &deg;</span><a href="{% url 'deals:alllist' %}view/{{ data.identity }}">{{ data.title }}</a></td></tr>
                                {% endfor %}
                                </tbody>
                            </table>
                            <table id="snapshot-table-2" class="snapshot-table">
                                <tbody>
                                {% for data in params.sidebar.hotweekly %}
                                    <tr><td><span class="snapshot-temp">{{ data.temperature }} &deg;</span><a href="{% url 'deals:alllist' %}view/{{ data.identity }}">{{ data.title }}</a></td></tr>
                                {% endfor %}
                                </tbody>
                            </table>
                            <table id="snapshot-table-3" class="snapshot-table">
                                <tbody>
                                {% for data in params.sidebar.hotmonthly %}
                                    <tr><td><span class="snapshot-temp">{{ data.temperature }} &deg;</span><a href="{% url 'deals:alllist' %}view/{{ data.identity }}">{{ data.title }}</a></td></tr>
                                {% endfor %}
                                </tbody>
                            </table>
                            <table id="snapshot-table-4" class="snapshot-table">
                                <tbody>
                                {% for data in params.sidebar.hotalltime %}
                                    <tr><td><span class="snapshot-temp">{{ data.temperature }} &deg;</span><a href="{% url 'deals:alllist' %}view/{{ data.identity }}">{{ data.title }}</a></td></tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                {% endblock sidebar_snapshot %}
            </div>
            {% endblock sidebar %}
        </div>
    </div>
</div>
<!-- Footer -->
{% block footer %}
<div class="row" id="footer">
    <div id="footer-wrap">
        <div class="large-3 columns footer-row">
            <h5>STATS</h5>
            <p><span class="footer-content-title">USERS ONLINE           </span><span class="footer-content-value"> : &nbsp;&nbsp;{{ params.footer.users_online }}</span></p>
            <p><span class="footer-content-title">REGISTERED USERS </span><span class="footer-content-value"> : &nbsp;&nbsp;{{ params.footer.total_reg_users }} </span></p>
            <p><span class="footer-content-title">MAX USERS ONLINE </span><span class="footer-content-value"> : &nbsp;&nbsp;{{ params.footer.max_users_online }}</span></p>
            <p><span class="footer-content-title">TOTAL POSTS</span><span class="footer-content-value"> : &nbsp;&nbsp;{{ params.footer.total_posts }}</span></p>
        </div>
        <div class="large-9 columns footer-row">
            <h5>ABOUT BOD</h5>
            <p>BOD - Is a community for sharing deals with the comunity. With rising Internet Portals in India, we felt trusted place to e-share deals is required and that's how BOD
                    was born. BOD is not a regular site where admins promote deals, this is a site driven by community. If you feel price of a product is lower at some place and could benefit others
                    come here and share it. So others like you can get benefited.
            </p>
        </div>
    </div>
</div>
{% endblock footer %}

<div id="overlay"></div>
<div id="message_box">
    <span id="close_box" class="centered">Click this box or press escape to close this window</span>
    <p id="message_box_msg"></p>
</div>



<script>
	  document.write('<script src=' +
	  ('__proto__' in {} ? 'js/vendor/zepto' : 'js/vendor/jquery') +
	  '.js><\/script>')
	  </script>

  <script src="js/foundation.min.js"></script>

</body>

</html>